### ISSUE TITLE
Why this repo? Since, NCIT Ultimate Notes is already there.

### ISSUE THREAD

**Issue by SatyaRajAwasth1** [anishkn04/NCIT_Resources#1]
@anishkn04 Can you please drop the motivation behind this repo. As [NCIT Ultimate Resources](https://github.com/theonlyNischal/Ultimate-Notes-Books-Resources-for-NCIT) is already there.

I always believe on collaboration and think open source also suggests that. So, contributing to make things that already exists better should be our inspiration.

**Comment by anishkn04** [comment]
Few reasons:
1. "Too much sugar tastes sour", I realize that it has many resources, but it actually has too much resources.
2. The syllabus changed starting from 2022 Fall, so this repo here is on the basis of that syllabus (Not that it changes much, but the subjects are in respective folders thus easier to navigate through)
3. (Khaas aafaile personal use ko laagi drive maa raakhya thiye ahile samma, ahile drive full huna laagera yeta transfer haanya 😭)
